version: "0.1"
services :
  sesac-torch:
    image : ysm2820/sesac-jenkins-test
    ports : 
      - 5001:5000
    volumes : 
      - /home/sumin.yang/jenkins:/home
    environment:
      - STAGE = DEV

